FROM node:18-alpine AS builder

WORKDIR /app

# Accept build arguments
ARG MONGODB_URI
ARG JWT_SECRET
ARG NODE_ENV=production
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG ADMIN_EMAIL
ARG ADMIN_PASSWORD
ARG NEXT_PUBLIC_ADMIN_EMAIL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG LINKEDIN_CLIENT_ID
ARG LINKEDIN_CLIENT_SECRET
ARG NEXT_PUBLIC_API_URL
ARG PYTHON_AI_API_URL
ARG PYTHON_OCR_API_URL
ARG EMAIL_PROVIDER
ARG GMAIL_USER
ARG GMAIL_APP_PASSWORD
ARG SENDGRID_API_KEY
ARG SENDGRID_FROM_EMAIL
ARG TWILIO_ACCOUNT_SID
ARG TWILIO_AUTH_TOKEN
ARG TWILIO_PHONE_NUMBER
ARG KAGGLE_API_TOKEN
ARG CLOUDINARY_CLOUD_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET
ARG CRON_SECRET
ARG GROQ_API_KEY

# Set environment variables from arguments
ENV MONGODB_URI=$MONGODB_URI
ENV JWT_SECRET=$JWT_SECRET
ENV NODE_ENV=$NODE_ENV
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV ADMIN_EMAIL=$ADMIN_EMAIL
ENV ADMIN_PASSWORD=$ADMIN_PASSWORD
ENV NEXT_PUBLIC_ADMIN_EMAIL=$NEXT_PUBLIC_ADMIN_EMAIL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV LINKEDIN_CLIENT_ID=$LINKEDIN_CLIENT_ID
ENV LINKEDIN_CLIENT_SECRET=$LINKEDIN_CLIENT_SECRET
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV PYTHON_AI_API_URL=$PYTHON_AI_API_URL
ENV PYTHON_OCR_API_URL=$PYTHON_OCR_API_URL
ENV EMAIL_PROVIDER=$EMAIL_PROVIDER
ENV GMAIL_USER=$GMAIL_USER
ENV GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD
ENV SENDGRID_API_KEY=$SENDGRID_API_KEY
ENV SENDGRID_FROM_EMAIL=$SENDGRID_FROM_EMAIL
ENV TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
ENV TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
ENV TWILIO_PHONE_NUMBER=$TWILIO_PHONE_NUMBER
ENV KAGGLE_API_TOKEN=$KAGGLE_API_TOKEN
ENV CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME
ENV CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
ENV CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET
ENV CRON_SECRET=$CRON_SECRET
ENV GROQ_API_KEY=$GROQ_API_KEY

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --frozen-lockfile

# Copy source
COPY . .

# Build Next.js app
RUN npm run build

# Production stage
FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install production dependencies only
RUN npm install --only=production

# Copy built app from builder
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

# Expose port
EXPOSE 3000

# Start app
CMD ["npm", "start"]
