import mongoose from 'mongoose';

// Store ML model predictions for patients
const SideEffectPredictionSchema = new mongoose.Schema({
  patient_id: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  medicine_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Medicine', required: true },
  
  // Patient Context (snapshot at prediction time)
  patient_snapshot: {
    age: Number,
    weight: Number,
    height: Number,
    gender: String,
    chronic_conditions: [String],
    current_medications: [String],
    allergies: [String],
    kidney_function: String, // "normal", "mild_impairment", "severe_impairment"
    liver_function: String
  },
  
  // ML Model Predictions
  predicted_side_effects: [{
    side_effect_name: String,
    base_probability: Number, // From medicine database
    adjusted_probability: Number, // Personalized by ML model
    confidence_score: Number, // ML model confidence 0-1
    risk_factors: [{
      factor: String, // "age", "drug_interaction", "chronic_condition"
      contribution: Number, // How much this factor increased risk
      description: String
    }],
    severity: String,
    onset_time: String, // "immediate", "hours", "days", "weeks"
    management_advice: String
  }],
  
  // Drug Interaction Risks (if multiple medications)
  interaction_risks: [{
    interacting_medicine: String,
    severity: String,
    risk_score: Number,
    warning: String,
    recommendation: String
  }],
  
  // Overall Risk Assessment
  overall_risk_score: Number, // 0-1, weighted average
  risk_category: { type: String, enum: ['low', 'moderate', 'high', 'very_high'] },
  
  // Recommendations
  recommendations: {
    is_safe_to_take: Boolean,
    requires_doctor_consultation: Boolean,
    dosage_adjustment_needed: Boolean,
    monitoring_required: Boolean,
    warnings: [String],
    precautions: [String]
  },
  
  // ML Model Info
  model_version: String,
  prediction_date: { type: Date, default: Date.now },
  
  // Feedback Loop (for model improvement)
  actual_side_effects_reported: [{
    side_effect: String,
    severity: String,
    reported_date: Date
  }],
  
  disclaimer: {
    type: String,
    default: "This prediction is generated by AI and should not replace professional medical advice. Always consult your doctor before taking any medication."
  }
});

// Indexes
SideEffectPredictionSchema.index({ patient_id: 1, medicine_id: 1 });
SideEffectPredictionSchema.index({ prediction_date: -1 });

export default mongoose.models.SideEffectPrediction || mongoose.model('SideEffectPrediction', SideEffectPredictionSchema);
